/* GENERATED by tools/gen_engine_config.py from
 * config/engine.toml - do not edit by hand.
 *
 * Analog sensor descriptors. src/sensor.c walks this table with
 * three conversion kernels; adding a sensor is a config edit.
 *
 * Every full-scale count below is DERIVED from the real divider
 * resistors, never typed in, and every divider was cross-checked
 * against ecu-pcb/build_schematic.py at generation time. */
#ifndef SENSOR_DEFS_H
#define SENSOR_DEFS_H

#include <stdint.h>

#define ADC_VREF_MV     3300u
#define ADC_MAX_COUNTS  4095u

/* Resistance (ohms) -> temperature (hundredths of a degree C),
 * resistance descending. */
typedef struct { uint32_t ohms; int16_t centi_c; } curve_point_t;

#define CURVE_GM_THERMISTOR_COUNT 14u
static const curve_point_t CURVE_GM_THERMISTOR[CURVE_GM_THERMISTOR_COUNT] = {
    {  100700u,  -4000 },
    {   47600u,  -2889 },
    {   24000u,  -1778 },
    {   12800u,   -667 },
    {    7190u,    444 },
    {    4220u,   1556 },
    {    2238u,   3000 },
    {    1590u,   3778 },
    {    1000u,   4889 },
    {     653u,   6000 },
    {     437u,   7111 },
    {     300u,   8222 },
    {     210u,   9333 },
    {     177u,   9900 },
};

typedef enum {
    SENSOR_KIND_LINEAR = 0,
    SENSOR_KIND_VOLTAGE,
    SENSOR_KIND_THERMISTOR
} sensor_kind_t;

typedef struct {
    const char         *name;
    sensor_kind_t       kind;
    /* linear/voltage: engineering value at 0 counts and at
     * counts_at_full, which is derived from the divider. */
    /* linear/voltage: the engineering values at the two ends
     * of the sensor's real signal band, and where that band
     * lands in ADC codes. counts_lo may be GREATER than
     * counts_hi - an inverted sensor falls as the measured
     * quantity rises, which is a real and common pattern. */
    int32_t             at_lo;
    int32_t             at_hi;
    uint16_t            counts_lo;
    uint16_t            counts_hi;
    /* Outside these the reading is not a value, it is a
     * broken wire or a short. */
    uint16_t            fault_lo;
    uint16_t            fault_hi;
    /* thermistor: pull-up and the curve to walk. */
    uint32_t            pullup_ohms;
    const curve_point_t *curve;
    uint8_t             curve_count;
} sensor_def_t;

typedef enum {
    SENSOR_APP1,
    SENSOR_APP2,
    SENSOR_CLT,
    SENSOR_FUELP,
    SENSOR_IAT,
    SENSOR_MAP,
    SENSOR_OILP,
    SENSOR_TPS,
    SENSOR_TPS1,
    SENSOR_TPS2,
    SENSOR_VBATT,
    SENSOR_COUNT
} sensor_id_t;

static const sensor_def_t SENSOR_DEFS[SENSOR_COUNT] = {
    /* app1   0.01%, band 310..2793 counts, uses 61% of ADC range */
    { "app1", SENSOR_KIND_LINEAR, 0, 10000, 310u, 2793u, 155u, 2948u, 0u, 0, 0 },
    /* app2   0.01%, band 310..1552 counts, uses 30% of ADC range */
    { "app2", SENSOR_KIND_LINEAR, 0, 10000, 310u, 1552u, 155u, 1707u, 0u, 0, 0 },
    /* clt */ { "clt", SENSOR_KIND_THERMISTOR,
        0, 0, 0u, 0u, 0u, 4095u,
        1000u, CURVE_GM_THERMISTOR, CURVE_GM_THERMISTOR_COUNT },
    /* fuelp    kPa, band 310..2793 counts, uses 61% of ADC range */
    { "fuelp", SENSOR_KIND_LINEAR, 0, 1000, 310u, 2793u, 155u, 2948u, 0u, 0, 0 },
    /* iat */ { "iat", SENSOR_KIND_THERMISTOR,
        0, 0, 0u, 0u, 0u, 4095u,
        4220u, CURVE_GM_THERMISTOR, CURVE_GM_THERMISTOR_COUNT },
    /* map      kPa, band 310..2793 counts, uses 61% of ADC range */
    { "map", SENSOR_KIND_LINEAR, 10, 105, 310u, 2793u, 155u, 2948u, 0u, 0, 0 },
    /* oilp     kPa, band 310..2793 counts, uses 61% of ADC range */
    { "oilp", SENSOR_KIND_LINEAR, 0, 1000, 310u, 2793u, 155u, 2948u, 0u, 0, 0 },
    /* tps    0.01%, band 310..2793 counts, uses 61% of ADC range */
    { "tps", SENSOR_KIND_LINEAR, 0, 10000, 310u, 2793u, 155u, 2948u, 0u, 0, 0 },
    /* tps1   0.01%, band 310..2793 counts, uses 61% of ADC range */
    { "tps1", SENSOR_KIND_LINEAR, 0, 10000, 310u, 2793u, 155u, 2948u, 0u, 0, 0 },
    /* tps2   0.01%, band 2793..310 counts, uses 61% of ADC range */
    { "tps2", SENSOR_KIND_LINEAR, 0, 10000, 2793u, 310u, 155u, 2948u, 0u, 0, 0 },
    /* vbatt     mV, band 0..4095 counts, uses 100% of ADC range */
    { "vbatt", SENSOR_KIND_VOLTAGE, 0, 25740, 0u, 4095u, 0u, 4095u, 0u, 0, 0 },
};

/* ---- Redundant pairs ------------------------------------------
 * Channels that measure the same physical quantity twice, so a
 * single failure can be caught by disagreement. The generator
 * has already refused any pair whose transfer functions are not
 * distinguishable - identical channels detect an open circuit
 * and nothing else. */
typedef struct {
    sensor_id_t a;
    sensor_id_t b;
    int32_t     tolerance;   /* in the pair's own unit */
} redundant_pair_t;

#define REDUNDANT_PAIR_COUNT 2u
static const redundant_pair_t REDUNDANT_PAIRS[REDUNDANT_PAIR_COUNT] = {
    { SENSOR_APP1, SENSOR_APP2, 500 },
    { SENSOR_TPS1, SENSOR_TPS2, 500 },
};

#endif /* SENSOR_DEFS_H */
